apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iy4s
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-iy4s@sha256:6fa49541ba487254ea64e5de3147608db4757a2b80485304a8ec0e5835d7746c
        name: my-nodejs
        resources: {}
status: {}
